// ─────────────────────────────────────────────
// Base de données des événements historiques
// Indexés par minute du jour (HH:mm)
// 160+ événements couvrant toute l'histoire mondiale
// ─────────────────────────────────────────────

export interface StaticEvent {
  minute: string
  year: number
  title: string
  description: string
  curiosity: string
  category: "Science" | "Politique" | "Culture" | "Sport" | "Tragédie" | "Exploration" | "Technologie" | "Art"
}

export const HISTORICAL_EVENTS: StaticEvent[] = [
  // ── 00:xx ──────────────────────────────────────────────────────────────────
  {
    minute: "00:00",
    year: 2000,
    title: "Passage au Nouveau Millénaire",
    description: "À minuit le 1er janvier 2000, le monde bascula dans un nouveau millénaire sous une explosion de célébrations. Le bug Y2K ne provoqua aucun chaos.",
    curiosity: "Des gouvernements stockèrent eau et vivres par peur d'une apocalypse numérique. Il ne se passa presque rien.",
    category: "Culture",
  },
  {
    minute: "00:17",
    year: 1903,
    title: "Premier Vol Motorisé de l'Histoire",
    description: "Le 17 décembre 1903, Orville Wright effectue le premier vol motorisé de l'histoire — 12 secondes, 36 mètres. L'ère de l'aviation était née.",
    curiosity: "L'avion 'Flyer' pesait 274 kg. Les frères Wright étaient réparateurs de vélos sans diplôme d'ingénieur.",
    category: "Technologie",
  },
  {
    minute: "00:41",
    year: 1820,
    title: "Découverte de l'Antarctique",
    description: "Le 27 janvier 1820, l'explorateur russe Fabian von Bellingshausen aperçoit pour la première fois le continent antarctique depuis son navire.",
    curiosity: "L'Antarctique contient 70% de l'eau douce de la planète, piégée dans sa calotte glaciaire vieille de 15 millions d'années.",
    category: "Exploration",
  },
  // ── 01:xx ──────────────────────────────────────────────────────────────────
  {
    minute: "01:11",
    year: 1991,
    title: "Début de la Guerre du Golfe",
    description: "Le 17 janvier 1991 à 01h00, la coalition internationale déclenche l'opération 'Tempête du désert' pour libérer le Koweït envahi par l'Irak.",
    curiosity: "C'était la première guerre diffusée en direct à la télévision mondiale. CNN couvrait les bombardements en temps réel depuis Bagdad.",
    category: "Politique",
  },
  {
    minute: "01:41",
    year: 1969,
    title: "Woodstock — Dernier Accord",
    description: "Le festival de Woodstock rassembla 400 000 personnes dans une ferme de New York. Jimi Hendrix clôtura le festival au petit matin.",
    curiosity: "Jimi Hendrix joua l'hymne américain à la guitare le dernier matin, en plein délire psychédélique, devant 180 000 spectateurs restants.",
    category: "Culture",
  },
  {
    minute: "01:56",
    year: 1886,
    title: "Dépôt du Brevet de l'Automobile",
    description: "Le 29 janvier 1886, Karl Benz dépose le brevet de la Motorwagen, première automobile à moteur à combustion interne de l'histoire.",
    curiosity: "C'est l'épouse de Benz, Bertha, qui effectua le premier long voyage en voiture (104 km) sans que son mari ne le sache.",
    category: "Technologie",
  },
  // ── 02:xx ──────────────────────────────────────────────────────────────────
  {
    minute: "02:20",
    year: 1912,
    title: "Le Titanic Disparaît sous les Flots",
    description: "Le 15 avril 1912 à 02h20, le RMS Titanic s'abîme dans l'Atlantique après avoir heurté un iceberg. 1517 personnes perdent la vie.",
    curiosity: "Le cuisinier en chef Charles Joughin survécut dans l'eau glaciale pendant 2 heures, attribuant sa survie au whisky qu'il avait bu.",
    category: "Tragédie",
  },
  {
    minute: "02:46",
    year: 2011,
    title: "Séisme de Tōhoku",
    description: "Le 11 mars 2011, un séisme de magnitude 9.1 frappe le Japon, déclenchant un tsunami et la catastrophe nucléaire de Fukushima.",
    curiosity: "La secousse était si puissante qu'elle déplaça l'axe de la Terre de 17 cm et raccourcit la journée de 1,8 microseconde.",
    category: "Tragédie",
  },
  // ── 03:xx ──────────────────────────────────────────────────────────────────
  {
    minute: "03:15",
    year: 1955,
    title: "Rosa Parks — L'Acte de Résistance",
    description: "Le 1er décembre 1955, Rosa Parks refuse de céder son siège à un homme blanc dans un bus de Montgomery, déclenchant le mouvement des droits civiques.",
    curiosity: "Rosa Parks n'était pas simplement fatiguée, comme le mythe le dit. Elle était une militante aguerrie qui décida consciemment d'agir.",
    category: "Politique",
  },
  {
    minute: "03:33",
    year: 1776,
    title: "Nuit de la Rédaction de la Déclaration",
    description: "Thomas Jefferson rédigea la Déclaration d'Indépendance américaine en 17 jours. Les travaux nocturnes façonnèrent un document qui allait changer l'histoire.",
    curiosity: "Jefferson avait 33 ans quand il rédigea la Déclaration. Il était si perfectionniste qu'il fit 86 révisions avant la version finale.",
    category: "Politique",
  },
  // ── 04:xx ──────────────────────────────────────────────────────────────────
  {
    minute: "04:00",
    year: 1968,
    title: "Assassinat de Martin Luther King",
    description: "Le 4 avril 1968 à 18h01, Martin Luther King Jr. est assassiné sur le balcon du Lorraine Motel à Memphis, Tennessee.",
    curiosity: "La veille, il avait prononcé 'I've been to the mountaintop', comme s'il pressentait sa mort imminente.",
    category: "Tragédie",
  },
  {
    minute: "04:44",
    year: 1867,
    title: "Achat de l'Alaska par les États-Unis",
    description: "Le 30 mars 1867, les États-Unis achètent l'Alaska à la Russie pour 7,2 millions de dollars. La presse ridiculise l'achat, l'appelant 'Seward's Folly'.",
    curiosity: "L'Alaska fut acheté pour 2 cents l'acre. Aujourd'hui, la valeur des ressources pétrolières seules dépasse 500 milliards de dollars.",
    category: "Politique",
  },
  // ── 05:xx ──────────────────────────────────────────────────────────────────
  {
    minute: "05:29",
    year: 1945,
    title: "Trinity — Premier Test Nucléaire",
    description: "Le 16 juillet 1945 à 05h29, la première bombe atomique 'Trinity' est détonée dans le désert du Nouveau-Mexique.",
    curiosity: "Oppenheimer murmura : 'Je suis devenu la Mort, le destructeur des mondes.' La chaleur de l'explosion vitrifia le sable environnant.",
    category: "Technologie",
  },
  {
    minute: "05:55",
    year: 1993,
    title: "Signature des Accords d'Oslo",
    description: "Le 13 septembre 1993, Yasser Arafat et Yitzhak Rabin signent les Accords d'Oslo sur la pelouse de la Maison Blanche.",
    curiosity: "La poignée de main entre Arafat et Rabin, encouragée par Clinton, fut l'une des images les plus emblématiques de la fin du XXe siècle.",
    category: "Politique",
  },
  // ── 06:xx ──────────────────────────────────────────────────────────────────
  {
    minute: "06:06",
    year: 1944,
    title: "D-Day — Débarquement en Normandie",
    description: "Le 6 juin 1944, les forces alliées débarquent sur les plages de Normandie dans la plus grande opération amphibie de l'histoire militaire.",
    curiosity: "156 000 soldats débarquèrent le premier jour. Le nom de code 'Overlord' fut choisi personnellement par Churchill.",
    category: "Politique",
  },
  {
    minute: "06:28",
    year: 1914,
    title: "Assassinat de François-Ferdinand",
    description: "Le 28 juin 1914 à Sarajevo, l'assassinat de l'archiduc François-Ferdinand déclenche la chaîne d'événements menant à la Grande Guerre.",
    curiosity: "L'assassin Gavrilo Princip, 19 ans, mangeait un sandwich après l'échec d'une première tentative quand la voiture de l'archiduc repassa devant lui.",
    category: "Politique",
  },
  {
    minute: "06:52",
    year: 1963,
    title: "Discours 'Ich bin ein Berliner'",
    description: "Le 26 juin 1963, John F. Kennedy prononce son célèbre discours 'Ich bin ein Berliner' devant 450 000 Berlinois au pied du Mur.",
    curiosity: "Kennedy avait appris la phrase phonétiquement en 2 minutes. Ses conseillers lui avaient écrit sur une feuille de papier qu'il tint dans sa main.",
    category: "Politique",
  },
  // ── 07:xx ──────────────────────────────────────────────────────────────────
  {
    minute: "07:30",
    year: 1687,
    title: "Principia Mathematica de Newton",
    description: "En juillet 1687, Newton publie ses 'Principia Mathematica', posant les bases de la mécanique classique et de la gravitation universelle.",
    curiosity: "La pomme de Newton n'est probablement qu'une légende. Newton lui-même dit qu'il 'observait' une pomme tomber en réfléchissant à la gravité.",
    category: "Science",
  },
  {
    minute: "07:48",
    year: 1961,
    title: "Youri Gagarine Quitte la Terre",
    description: "Le 12 avril 1961, Youri Gagarine devient le premier être humain à voyager dans l'espace, orbitant la Terre en 108 minutes.",
    curiosity: "Gagarine aurait dit 'Poyekhali!' (En avant!) au décollage. Il avait 27 ans et n'était pas certain de survivre au voyage.",
    category: "Exploration",
  },
  {
    minute: "07:59",
    year: 1830,
    title: "Révolution de Juillet en France",
    description: "Du 27 au 29 juillet 1830, les 'Trois Glorieuses' chassent Charles X du trône et instaurent la monarchie de Juillet sous Louis-Philippe.",
    curiosity: "Eugène Delacroix peignit 'La Liberté guidant le peuple' pour immortaliser ces trois jours. Il n'avait pourtant pas participé à l'insurrection.",
    category: "Politique",
  },
  // ── 08:xx ──────────────────────────────────────────────────────────────────
  {
    minute: "08:00",
    year: 1945,
    title: "VE Day — Victoire en Europe",
    description: "Le 8 mai 1945, l'Allemagne signe sa capitulation inconditionnelle. Des millions de personnes célèbrent la fin de la guerre en Europe.",
    curiosity: "Churchill annonça la capitulation à 15h00. Des foules immenses se rassemblèrent à Times Square, à Trafalgar Square et sur les Champs-Élysées.",
    category: "Politique",
  },
  {
    minute: "08:15",
    year: 1945,
    title: "Hiroshima — L'Instant Zéro",
    description: "Le 6 août 1945 à 08h15, la bombe 'Little Boy' explose à 580 mètres au-dessus d'Hiroshima, tuant instantanément 80 000 personnes.",
    curiosity: "L'ombre d'un homme assis sur des marches fut gravée dans la pierre par l'éclair de l'explosion. Elle est visible encore aujourd'hui.",
    category: "Tragédie",
  },
  {
    minute: "08:35",
    year: 1519,
    title: "Cortés Débarque au Mexique",
    description: "En avril 1519, Hernán Cortés débarque sur les côtes mexicaines avec 508 soldats pour conquérir un empire aztèque de plusieurs millions d'habitants.",
    curiosity: "Pour empêcher ses hommes de fuir, Cortés fit brûler ses propres navires. Ses soldats n'avaient d'autre choix que de vaincre ou mourir.",
    category: "Exploration",
  },
  // ── 09:xx ──────────────────────────────────────────────────────────────────
  {
    minute: "09:02",
    year: 1995,
    title: "Attentat d'Oklahoma City",
    description: "Le 19 avril 1995, une bombe détruit le bâtiment fédéral Alfred P. Murrah à Oklahoma City, tuant 168 personnes dont 19 enfants.",
    curiosity: "C'était le plus grand attentat terroriste sur le sol américain avant le 11 septembre. L'auteur était un citoyen américain d'extrême droite.",
    category: "Tragédie",
  },
  {
    minute: "09:11",
    year: 2001,
    title: "Attentats du 11 Septembre — Le Monde Bascule",
    description: "Le 11 septembre 2001, des attaques terroristes frappent les États-Unis. Deux avions percutent les tours du World Trade Center à New York.",
    curiosity: "Les tours jumelles mirent 102 minutes pour s'effondrer. L'attentat changea définitivement la géopolitique, la sécurité aérienne et la vie quotidienne mondiale.",
    category: "Tragédie",
  },
  {
    minute: "09:45",
    year: 1852,
    title: "Naissance de la Première Machine à Coudre",
    description: "Isaac Singer dépose le brevet de sa machine à coudre améliorée, révolutionnant l'industrie textile et le travail des femmes au XIXe siècle.",
    curiosity: "Singer vendit sa machine à crédit, inventant ainsi le système de vente à tempérament. Il eut 18 enfants de 5 femmes différentes.",
    category: "Technologie",
  },
  // ── 10:xx ──────────────────────────────────────────────────────────────────
  {
    minute: "10:00",
    year: 1961,
    title: "Gagarine — Retour sur Terre",
    description: "Le 12 avril 1961, après 108 minutes dans l'espace, Youri Gagarine atterrit en parachute dans la steppe russe, devenant une légende mondiale.",
    curiosity: "Le vol a duré exactement 1h48. Gagarine orna la une de 700 journaux à travers le monde et mourut 7 ans plus tard dans un accident d'avion.",
    category: "Exploration",
  },
  {
    minute: "10:30",
    year: 1492,
    title: "Christophe Colomb Aperçoit les Amériques",
    description: "Le 12 octobre 1492, Christophe Colomb aperçoit pour la première fois les côtes des Bahamas, croyant avoir atteint les Indes orientales.",
    curiosity: "Colomb mourut en 1506 sans jamais savoir qu'il avait découvert un nouveau continent. Il pensait avoir trouvé une route vers l'Asie.",
    category: "Exploration",
  },
  {
    minute: "10:48",
    year: 1994,
    title: "Inauguration du Tunnel sous la Manche",
    description: "Le 6 mai 1994, le tunnel sous la Manche est inauguré, reliant pour la première fois la Grande-Bretagne au continent européen par voie terrestre.",
    curiosity: "50 km de long dont 38 sous la mer, 13 000 ouvriers, 7 ans de travaux. Les deux équipes de creusement se rejoignirent le 1er décembre 1990.",
    category: "Technologie",
  },
  // ── 11:xx ──────────────────────────────────────────────────────────────────
  {
    minute: "11:00",
    year: 1918,
    title: "Armistice — La Grande Guerre s'Achève",
    description: "Le 11 novembre 1918 à 11h00, le cessez-le-feu entre en vigueur, mettant fin à quatre ans de Première Guerre Mondiale.",
    curiosity: "Le dernier soldat tué tomba à 10h59, une minute avant l'armistice. 17 millions de morts, 21 millions de blessés — la 'Der des Ders'.",
    category: "Politique",
  },
  {
    minute: "11:11",
    year: 1918,
    title: "11h11 — La Minute du Souvenir Éternel",
    description: "11h11 du 11 novembre 1918 : l'heure symbolique de l'armistice, devenue une minute de silence universelle dans le monde entier.",
    curiosity: "Cette triple répétition du chiffre 11 est considérée comme la combinaison numérique la plus symbolique de l'histoire contemporaine.",
    category: "Culture",
  },
  {
    minute: "11:37",
    year: 1859,
    title: "Darwin Publie l'Origine des Espèces",
    description: "Le 24 novembre 1859, Charles Darwin publie 'De l'origine des espèces', révolutionnant notre compréhension de la vie sur Terre.",
    curiosity: "Darwin hésita 20 ans à publier par peur du scandale religieux. Le jour de publication, les 1250 exemplaires furent épuisés en quelques heures.",
    category: "Science",
  },
  // ── 12:xx ──────────────────────────────────────────────────────────────────
  {
    minute: "12:00",
    year: 1963,
    title: "Assassinat de JFK — Dallas",
    description: "Le 22 novembre 1963 à 12h30, le président Kennedy est assassiné lors d'un défilé à Dallas. Le monde entier est sous le choc.",
    curiosity: "La vidéo de 26 secondes filmée par Abraham Zapruder est l'une des plus analysées de l'histoire. Lee Harvey Oswald fut tué deux jours plus tard.",
    category: "Politique",
  },
  {
    minute: "12:21",
    year: 1989,
    title: "Chute du Mur de Berlin",
    description: "Le 9 novembre 1989, les Berlinois commencent à démolir le Mur dans une euphorie collective, effaçant 28 ans de division.",
    curiosity: "Le mur faisait 155 km, était gardé par 302 tours et 10 000 soldats. 171 personnes sont mortes en tentant de le franchir.",
    category: "Politique",
  },
  {
    minute: "12:34",
    year: 2009,
    title: "12:34:56 — L'Instant Numérique Parfait",
    description: "Le 7 août 2009 à 12:34:56, les mathématiciens célébrèrent l'alignement parfait des chiffres 1-2-3-4-5-6-7-8-9 dans la date et l'heure.",
    curiosity: "Ce moment unique ne se reproduira pas avant le 7 août 2109, dans cent ans. Des fêtes furent organisées partout dans le monde.",
    category: "Culture",
  },
  {
    minute: "12:59",
    year: 1972,
    title: "Fischer bat Spassky — Le Match du Siècle",
    description: "En juillet 1972 à Reykjavik, Bobby Fischer bat Boris Spassky aux échecs dans ce qui fut appelé 'le match du siècle' de la Guerre Froide.",
    curiosity: "Fischer exigea 50% des droits TV avant de jouer et fut en retard à presque toutes les parties. Son comportement erratique fit partie de sa stratégie.",
    category: "Sport",
  },
  // ── 13:xx ──────────────────────────────────────────────────────────────────
  {
    minute: "13:13",
    year: 1307,
    title: "Arrestation des Templiers — Vendredi 13",
    description: "Le vendredi 13 octobre 1307, le roi Philippe IV de France ordonne l'arrestation simultanée de tous les Templiers du royaume.",
    curiosity: "Cette date est l'une des origines possibles de la superstition du vendredi 13. Les Templiers gardaient peut-être le secret du Saint Graal.",
    category: "Culture",
  },
  {
    minute: "13:31",
    year: 1970,
    title: "Houston, Nous Avons un Problème",
    description: "Le 13 avril 1970 à 21h07, une explosion à bord d'Apollo 13 met les trois astronautes en danger de mort à 330 000 km de la Terre.",
    curiosity: "La phrase exacte était 'Houston, nous avons EU un problème.' Le film de Ron Howard changea au présent pour dramatiser.",
    category: "Exploration",
  },
  {
    minute: "13:45",
    year: 1815,
    title: "Napoléon Revient de l'Île d'Elbe",
    description: "Le 1er mars 1815, Napoléon Bonaparte débarque sur les côtes françaises avec 1050 hommes pour reconquérir son trône pendant les Cent-Jours.",
    curiosity: "Napoléon marcha seul vers des soldats envoyés pour l'arrêter et dit : 'Qui veut tirer sur son Empereur ?' Ils le rejoignirent tous.",
    category: "Politique",
  },
  // ── 14:xx ──────────────────────────────────────────────────────────────────
  {
    minute: "14:14",
    year: 1912,
    title: "Le Titanic Heurte l'Iceberg",
    description: "Le 14 avril 1912 à 23h40, la vigie Frederick Fleet aperçoit un iceberg. Il est trop tard. Le Titanic sombre en 2h40.",
    curiosity: "Les violonistes jouèrent jusqu'au bout. Le cuisinier Charles Joughin survécut 2 heures dans l'eau glaciale grâce au whisky.",
    category: "Tragédie",
  },
  {
    minute: "14:37",
    year: 1969,
    title: "Transmission Apollo 11 — Eagle a Atterri",
    description: "À 14h37 UTC le 20 juillet 1969, le module lunaire Eagle transmettait depuis la Mer de la Tranquillité. L'humanité venait de poser le pied sur la Lune.",
    curiosity: "La NASA avait préparé un discours funèbre si les astronautes restaient bloqués sur la Lune. Il ne fut jamais utilisé.",
    category: "Exploration",
  },
  {
    minute: "14:55",
    year: 1789,
    title: "Louis XVI Apprend la Prise de la Bastille",
    description: "Le soir du 14 juillet 1789, Louis XVI apprend la prise de la Bastille dans son journal : 'Rien.' Il pensait à la chasse.",
    curiosity: "Le mot 'rien' dans le journal de Louis XVI était une référence à la chasse. Il ne comprit pas immédiatement l'ampleur de la révolution.",
    category: "Politique",
  },
  // ── 15:xx ──────────────────────────────────────────────────────────────────
  {
    minute: "15:00",
    year: 1687,
    title: "La Gravitation Universelle de Newton",
    description: "Isaac Newton formule sa loi de la gravitation universelle, unifiant les mouvements terrestres et célestes en une seule et même théorie.",
    curiosity: "Newton mit 20 ans à publier ses découvertes. C'est Edmund Halley, l'astronome de la comète, qui finança l'impression des Principia.",
    category: "Science",
  },
  {
    minute: "15:15",
    year: 1564,
    title: "Naissance de Shakespeare",
    description: "William Shakespeare, le plus grand dramaturge de la langue anglaise, est baptisé le 26 avril 1564 à Stratford-upon-Avon.",
    curiosity: "Shakespeare inventa plus de 1 700 mots anglais : 'bedroom', 'lonely', 'generous', 'assassination', 'eyeball', 'swagger'.",
    category: "Art",
  },
  {
    minute: "15:42",
    year: 1955,
    title: "Fondation de McDonald's Corporation",
    description: "Le 15 avril 1955, Ray Kroc ouvre son premier McDonald's à Des Plaines, Illinois, lançant la plus grande révolution de la restauration rapide.",
    curiosity: "McDonald's sert aujourd'hui 69 millions de personnes par jour dans 100 pays. Le logo 'M' est l'une des marques les plus reconnues au monde.",
    category: "Culture",
  },
  // ── 16:xx ──────────────────────────────────────────────────────────────────
  {
    minute: "16:00",
    year: 1986,
    title: "Catastrophe de Tchernobyl",
    description: "Le 26 avril 1986 à 01h23, le réacteur 4 de Tchernobyl explose en Ukraine soviétique dans la pire catastrophe nucléaire civile de l'histoire.",
    curiosity: "La zone d'exclusion de 30 km est devenue un sanctuaire naturel paradoxal, avec une biodiversité exceptionnelle malgré la radioactivité.",
    category: "Tragédie",
  },
  {
    minute: "16:16",
    year: 1961,
    title: "Construction du Mur de Berlin Commence",
    description: "Le 13 août 1961 à 01h00, l'Allemagne de l'Est commence la construction du Mur de Berlin, coupant la ville en deux du jour au lendemain.",
    curiosity: "171 personnes moururent en tentant de franchir le mur en 28 ans. Des tunnels secrets, des planeurs et même un sous-marin furent utilisés.",
    category: "Politique",
  },
  {
    minute: "16:30",
    year: 1975,
    title: "Chute de Saïgon — Fin du Vietnam",
    description: "Le 30 avril 1975, Saïgon tombe aux mains du Nord Vietnam. Les derniers Américains sont évacués par hélicoptère depuis l'ambassade.",
    curiosity: "L'opération 'Frequent Wind' fut la plus grande évacuation en hélicoptère de l'histoire : 81 appareils pour 7000 personnes en 18 heures.",
    category: "Politique",
  },
  // ── 17:xx ──────────────────────────────────────────────────────────────────
  {
    minute: "17:17",
    year: 1789,
    title: "Prise de la Bastille",
    description: "Le 14 juillet 1789, le peuple de Paris prend d'assaut la forteresse de la Bastille, déclenchant la Révolution française.",
    curiosity: "Seulement 7 prisonniers étaient détenus à la Bastille lors de sa prise. Le symbole était plus fort que la réalité.",
    category: "Politique",
  },
  {
    minute: "17:33",
    year: 1939,
    title: "Début de la Seconde Guerre Mondiale",
    description: "Le 1er septembre 1939, l'Allemagne nazie envahit la Pologne. Deux jours plus tard, la France et le Royaume-Uni déclarent la guerre.",
    curiosity: "La campagne de Pologne dura 35 jours. Hitler avait parié que les Alliés ne réagiraient pas, comme lors de l'annexion de l'Autriche.",
    category: "Politique",
  },
  {
    minute: "17:58",
    year: 1999,
    title: "Lancement de Napster",
    description: "En juin 1999, Shawn Fanning, 18 ans, lance Napster, le premier service de partage de musique en peer-to-peer, révolutionnant l'industrie musicale.",
    curiosity: "À son apogée, Napster comptait 80 millions d'utilisateurs. Il fut fermé en 2001 après une bataille judiciaire avec Metallica et Dr. Dre.",
    category: "Technologie",
  },
  // ── 18:xx ──────────────────────────────────────────────────────────────────
  {
    minute: "18:00",
    year: 1776,
    title: "Déclaration d'Indépendance Américaine",
    description: "Le 4 juillet 1776, les 13 colonies américaines déclarent leur indépendance du Royaume-Uni, fondant les États-Unis d'Amérique.",
    curiosity: "John Adams et Thomas Jefferson moururent tous les deux le 4 juillet 1826, exactement 50 ans jour pour jour après la Déclaration.",
    category: "Politique",
  },
  {
    minute: "18:30",
    year: 1969,
    title: "Woodstock — Les Portes s'Ouvrent",
    description: "Le 15 août 1969, Woodstock ouvre ses portes à Bethel, New York. 400 000 personnes convergent pour 3 jours de musique et de paix.",
    curiosity: "32 artistes se produisirent, dont Janis Joplin, The Who, Grateful Dead et Santana — ce dernier en plein trip sous LSD.",
    category: "Culture",
  },
  {
    minute: "18:44",
    year: 1869,
    title: "Inauguration du Canal de Suez",
    description: "Le 17 novembre 1869, le canal de Suez est inauguré par l'impératrice Eugénie, réduisant la route maritime entre l'Europe et l'Asie de 7000 km.",
    curiosity: "Verdi composa l'opéra Aïda pour l'occasion mais ne le finit pas à temps. Il fut créé deux ans plus tard au Caire.",
    category: "Technologie",
  },
  // ── 19:xx ──────────────────────────────────────────────────────────────────
  {
    minute: "19:00",
    year: 1969,
    title: "Premier Message sur Internet — ARPANET",
    description: "Le 29 octobre 1969, le premier message est envoyé sur ARPANET. Le message 'lo' (pour 'login') fit planter le système après deux lettres.",
    curiosity: "La révolution numérique commença par un bégaiement. Le 'o' ne passa pas. La connexion planta. Mais le monde ne serait plus jamais le même.",
    category: "Technologie",
  },
  {
    minute: "19:19",
    year: 1953,
    title: "Watson & Crick Découvrent l'ADN",
    description: "Le 25 avril 1953, Watson et Crick publient la structure en double hélice de l'ADN dans la revue Nature, révolutionnant la biologie.",
    curiosity: "Rosalind Franklin avait pris la Photo 51, clé de la découverte, sans laquelle Watson et Crick n'auraient pas pu déduire la structure.",
    category: "Science",
  },
  {
    minute: "19:44",
    year: 1989,
    title: "Massacre de la Place Tian'anmen",
    description: "Le 4 juin 1989, l'armée chinoise réprime violemment les manifestations pro-démocratie sur la Place Tian'anmen à Pékin.",
    curiosity: "'L'Homme de Tian'anmen' qui bloqua seul une colonne de chars est l'une des photos les plus iconiques du XXe siècle. Son identité reste inconnue.",
    category: "Politique",
  },
  // ── 20:xx ──────────────────────────────────────────────────────────────────
  {
    minute: "20:17",
    year: 1969,
    title: "Premier Homme sur la Lune — Apollo 11",
    description: "Le 20 juillet 1969 à 20h17 UTC, le module lunaire Eagle se pose sur la Lune dans la Mer de la Tranquillité.",
    curiosity: "Armstrong avait moins de 30 secondes de carburant lors de l'alunissage. Il dut piloter manuellement pour éviter un champ de rochers.",
    category: "Exploration",
  },
  {
    minute: "20:20",
    year: 1969,
    title: "Armstrong Regarde la Terre depuis la Lune",
    description: "Depuis la surface lunaire, Neil Armstrong contempla la Terre, ce 'marbre bleu' suspendu dans le vide sidéral, et ressentit une émotion unique.",
    curiosity: "'Ce petit pas' fut regardé en direct par 600 millions de personnes — soit 1 humain sur 5 à l'époque. La transmission venait de la Lune.",
    category: "Exploration",
  },
  {
    minute: "20:45",
    year: 1905,
    title: "Einstein Écrit E=mc²",
    description: "En 1905, Albert Einstein formule son équation la plus célèbre, établissant l'équivalence entre la masse et l'énergie, fondant la physique nucléaire.",
    curiosity: "Einstein avait 26 ans et était examinateur de brevets à Berne. Son 'annus mirabilis' 1905 vit la publication de 4 articles révolutionnaires.",
    category: "Science",
  },
  // ── 21:xx ──────────────────────────────────────────────────────────────────
  {
    minute: "21:00",
    year: 1879,
    title: "Edison Allume la Première Ampoule",
    description: "Le 22 octobre 1879, Thomas Edison teste sa première ampoule électrique à incandescence, changeant définitivement le monde.",
    curiosity: "Edison testa plus de 6 000 matériaux pour le filament avant le succès. Son dicton : '1% d'inspiration, 99% de transpiration.'",
    category: "Technologie",
  },
  {
    minute: "21:21",
    year: 1969,
    title: "Neil Armstrong Pose le Pied sur la Lune",
    description: "À 02h56 UTC le 21 juillet 1969, Neil Armstrong pose le pied droit sur la surface lunaire et prononce sa phrase immortelle.",
    curiosity: "'Un petit pas pour l'homme, un bond de géant pour l'humanité.' Le signal radio avait 2,6 secondes de délai depuis la Lune.",
    category: "Exploration",
  },
  {
    minute: "21:37",
    year: 2007,
    title: "Lancement de l'iPhone",
    description: "Le 9 janvier 2007, Steve Jobs présente l'iPhone à la Macworld Conference. Un écran tactile, un iPod, un téléphone — une révolution.",
    curiosity: "Jobs garda l'iPhone secret même de la plupart des employés d'Apple. Le premier prototype ne fonctionnait qu'avec une seule application.",
    category: "Technologie",
  },
  // ── 22:xx ──────────────────────────────────────────────────────────────────
  {
    minute: "22:00",
    year: 1905,
    title: "La Relativité Restreinte d'Einstein",
    description: "En juin 1905, Einstein publie la théorie de la relativité restreinte, changeant notre conception du temps, de l'espace et de la lumière.",
    curiosity: "La conséquence la plus célèbre : E=mc². Cette formule, si simple en apparence, relie la matière et l'énergie à la vitesse de la lumière au carré.",
    category: "Science",
  },
  {
    minute: "22:22",
    year: 2002,
    title: "Inauguration de la Bibliotheca Alexandrina",
    description: "La Bibliotheca Alexandrina, renaissance de l'antique bibliothèque d'Alexandrie, ouvre ses portes en Égypte dans un bâtiment ultramoderne.",
    curiosity: "L'ancienne bibliothèque contenait potentiellement 700 000 rouleaux de papyrus. Sa destruction reste l'une des plus grandes pertes culturelles de l'Antiquité.",
    category: "Culture",
  },
  {
    minute: "22:47",
    year: 1963,
    title: "Mort d'Aldous Huxley et C.S. Lewis",
    description: "Le 22 novembre 1963, Aldous Huxley (Le Meilleur des Mondes) et C.S. Lewis (Narnia) moururent le même jour — noyés dans l'actualité de JFK.",
    curiosity: "Trois grands esprits du XXe siècle quittèrent le monde le même jour. La mort de Kennedy éclipsa totalement leurs disparitions.",
    category: "Culture",
  },
  // ── 23:xx ──────────────────────────────────────────────────────────────────
  {
    minute: "23:09",
    year: 1940,
    title: "Churchill Prononce 'We Shall Fight'",
    description: "Le 4 juin 1940, Churchill prononce son discours le plus célèbre devant le Parlement : 'We shall fight on the beaches...' face à Hitler.",
    curiosity: "Churchill prépara ce discours en buvant du whisky. Il termina en disant en aparté : 'Et nous les frapperons sur la tête avec des bouteilles vides, car c'est tout ce que nous aurons.'",
    category: "Politique",
  },
  {
    minute: "23:23",
    year: 1889,
    title: "Inauguration de la Tour Eiffel",
    description: "Le 31 mars 1889, la Tour Eiffel est inaugurée pour l'Exposition Universelle de Paris. Elle devait être démolie 20 ans plus tard.",
    curiosity: "Gustave Eiffel avait un appartement privé au sommet où il recevait des scientifiques, dont Thomas Edison qui lui offrit un phonographe.",
    category: "Art",
  },
  {
    minute: "23:59",
    year: 1999,
    title: "Dernière Minute du Millénaire",
    description: "23h59 le 31 décembre 1999 : la dernière minute du XXème siècle. Le monde retenait son souffle avant l'an 2000.",
    curiosity: "La France fut le dernier grand pays développé à fêter le millénaire, grâce au fuseau horaire. Paris Nuit Blanche accueillit 5 millions de personnes.",
    category: "Culture",
  },
  // ── Événements supplémentaires — couverture horaire complète ──────────────
  {
    minute: "00:23",
    year: 1944,
    title: "Débarquement de Normandie — Parachutistes",
    description: "Dans la nuit du 5 au 6 juin 1944, les parachutistes alliés sautent derrière les lignes ennemies en Normandie pour préparer le D-Day.",
    curiosity: "13 000 parachutistes sautèrent dans la nuit. Beaucoup atterrirent dans l'eau ou dans des marécages, certains ne jamais retrouvés.",
    category: "Politique",
  },
  {
    minute: "00:55",
    year: 1997,
    title: "Hong Kong Rétrocédé à la Chine",
    description: "Le 1er juillet 1997 à minuit, Hong Kong passe sous souveraineté chinoise après 156 ans de colonisation britannique.",
    curiosity: "Le Prince Charles, qui représentait la Couronne, pleura lors de la cérémonie. Le gouverneur Patten sanglota en quittant Hong Kong.",
    category: "Politique",
  },
  {
    minute: "01:23",
    year: 1986,
    title: "L'Explosion de Tchernobyl — Minute Exacte",
    description: "Le 26 avril 1986 à 01h23m58s, le réacteur 4 de la centrale de Tchernobyl explose, libérant 400 fois l'équivalent radioactif d'Hiroshima.",
    curiosity: "Les liquidateurs envoyés nettoyer reçurent jusqu'à 16 Grays de radiation. La dose létale est de 6 Grays. Ils savaient qu'ils mouraient.",
    category: "Tragédie",
  },
  {
    minute: "02:10",
    year: 1974,
    title: "Démission de Nixon Annoncée",
    description: "Le 8 août 1974, Richard Nixon annonce sa démission à la télévision suite au scandale du Watergate, la première démission d'un président américain.",
    curiosity: "Nixon avait commandé aux cambrioleurs de photographier les fichiers démocrates. L'un des cambrioleurs laissa du ruban adhésif sur une serrure.",
    category: "Politique",
  },
  {
    minute: "03:07",
    year: 1962,
    title: "John Glenn Orbite autour de la Terre",
    description: "Le 20 février 1962, John Glenn devient le premier Américain à orbiter autour de la Terre, effectuant 3 révolutions en 4h55.",
    curiosity: "Glenn emporta une caméra à bord. À son retour, il fut accueilli par 4 millions de personnes dans les rues de New York.",
    category: "Exploration",
  },
  {
    minute: "03:58",
    year: 1978,
    title: "Premier Bébé Éprouvette — Louise Brown",
    description: "Le 25 juillet 1978, Louise Brown naît à Oldham, Angleterre — premier être humain conçu par fécondation in vitro.",
    curiosity: "Les médecins Robert Edwards et Patrick Steptoe travaillèrent 12 ans sur la FIV. Edwards reçut le Nobel de médecine en 2010 (Steptoe était décédé).",
    category: "Science",
  },
  {
    minute: "04:28",
    year: 1945,
    title: "Mort de Mussolini",
    description: "Le 28 avril 1945, Benito Mussolini est capturé par des partisans communistes italiens et exécuté. Son corps est exposé la tête en bas à Milan.",
    curiosity: "Hitler apprit la mort de Mussolini le lendemain. Deux jours plus tard, il se suicidait dans son bunker à Berlin.",
    category: "Politique",
  },
  {
    minute: "05:00",
    year: 1804,
    title: "Napoléon se Couronne Empereur",
    description: "Le 2 décembre 1804, Napoléon Bonaparte se couronne Empereur des Français à Notre-Dame de Paris, arrachant la couronne des mains du Pape.",
    curiosity: "Napoléon se couronna lui-même pour signifier qu'il ne tenait son pouvoir que de lui-même. David peignit la scène sur 9,8 m × 6,2 m.",
    category: "Politique",
  },
  {
    minute: "05:48",
    year: 1961,
    title: "Bay of Pigs — Débarquement à Cuba",
    description: "Le 17 avril 1961, 1400 exilés cubains tentent de renverser Fidel Castro lors du débarquement de la Baie des Cochons — un fiasco total.",
    curiosity: "Kennedy refusa d'envoyer des avions de couverture. Les hommes furent capturés et échangés contre des médicaments d'une valeur de 53 millions de dollars.",
    category: "Politique",
  },
  {
    minute: "06:37",
    year: 1977,
    title: "Star Wars — Sortie en Salles",
    description: "Le 25 mai 1977, 'Star Wars' de George Lucas sort dans 32 salles américaines et révolutionne le cinéma de science-fiction pour toujours.",
    curiosity: "Lucas ne croyait pas au succès du film. Il céda les droits de merchandising à la Fox pour garder le contrôle créatif — une décision qui lui valut des milliards.",
    category: "Art",
  },
  {
    minute: "07:07",
    year: 1965,
    title: "Les Beatles sur Ed Sullivan",
    description: "Le 9 février 1964, les Beatles se produisent pour la première fois à la télévision américaine sur The Ed Sullivan Show devant 73 millions de téléspectateurs.",
    curiosity: "Ce soir-là, le taux de criminalité aux États-Unis chuta à son plus bas niveau historique. Tout le monde était devant sa télévision.",
    category: "Culture",
  },
  {
    minute: "07:23",
    year: 1492,
    title: "Christophe Colomb Quitte Palos",
    description: "Le 3 août 1492, Christophe Colomb appareille de Palos de la Frontera avec trois caravelles pour sa première traversée de l'Atlantique.",
    curiosity: "L'équipage était de 90 hommes répartis sur 3 navires. Colomb modifia le journal de bord pour minimiser la distance parcourue et éviter la mutinerie.",
    category: "Exploration",
  },
  {
    minute: "08:28",
    year: 1963,
    title: "Discours 'I Have a Dream' — MLK",
    description: "Le 28 août 1963, Martin Luther King Jr. prononce son discours 'I Have a Dream' devant 250 000 marcheurs à Washington D.C.",
    curiosity: "King improvisa la partie 'I Have a Dream' après l'avoir dit à la foule. Ce n'était pas dans son texte préparé. Mahalia Jackson lui cria 'Parle-leur du rêve !'",
    category: "Politique",
  },
  {
    minute: "09:30",
    year: 1929,
    title: "Krach de Wall Street — Jeudi Noir",
    description: "Le 24 octobre 1929, la bourse de New York s'effondre dans la Grande Dépression. 12,9 millions d'actions vendues en panique.",
    curiosity: "Le mythe des financiers se défenestrant est faux. Le taux de suicide n'augmenta pas anormalement ce jour-là. Mais la misère qui suivit fut réelle.",
    category: "Politique",
  },
  {
    minute: "09:58",
    year: 2001,
    title: "Effondrement de la Tour Sud du WTC",
    description: "Le 11 septembre 2001 à 09h59, la Tour Sud du World Trade Center s'effondre, 56 minutes après l'impact. La Tour Nord suivra 29 minutes après.",
    curiosity: "Le son des alarmes de détresse des pompiers piégés à l'intérieur fut enregistré et permet encore aujourd'hui d'identifier les victimes.",
    category: "Tragédie",
  },
  {
    minute: "10:17",
    year: 1933,
    title: "Hitler Prend le Pouvoir en Allemagne",
    description: "Le 30 janvier 1933, Adolf Hitler est nommé chancelier d'Allemagne par le président Hindenburg, ouvrant la voie au nazisme.",
    curiosity: "L'incendie du Reichstag 4 semaines plus tard servit de prétexte pour suspendre les libertés civiles. Hitler avait planifié l'incendie, selon certains historiens.",
    category: "Politique",
  },
  {
    minute: "10:55",
    year: 1977,
    title: "Elvis Presley Meurt à Graceland",
    description: "Le 16 août 1977, Elvis Presley est retrouvé mort dans sa salle de bain à Graceland. Le 'Roi du Rock' avait 42 ans.",
    curiosity: "L'autopsie révéla qu'Elvis prenait 10 médicaments différents par jour. Son décès attira 75 000 personnes devant Graceland en une nuit.",
    category: "Culture",
  },
  {
    minute: "11:22",
    year: 1963,
    title: "Lyndon B. Johnson Prête Serment",
    description: "Le 22 novembre 1963, à bord de l'Air Force One, Lyndon Johnson prête serment comme 36e président des États-Unis après la mort de Kennedy.",
    curiosity: "La photo de la cérémonie montre Jackie Kennedy en robe rose maculée du sang de son mari. Elle refusa de changer de tenue.",
    category: "Politique",
  },
  {
    minute: "11:55",
    year: 1962,
    title: "Marilyn Monroe Chante à JFK",
    description: "Le 19 mai 1962, Marilyn Monroe chante 'Happy Birthday Mr. President' à John F. Kennedy lors d'une soirée au Madison Square Garden.",
    curiosity: "Monroe porta une robe si serrée qu'elle dut être cousue sur elle. Kennedy dit après : 'Je peux mourir heureux maintenant.' Curieux présage.",
    category: "Culture",
  },
  {
    minute: "12:44",
    year: 1945,
    title: "Signature de la Capitulation du Japon",
    description: "Le 2 septembre 1945 à bord du USS Missouri, le Japon signe sa capitulation inconditionnelle, mettant fin à la Seconde Guerre Mondiale.",
    curiosity: "La cérémonie dura exactement 23 minutes. Les représentants japonais signèrent en silence. Douglas MacArthur présida avec cinq stylos différents.",
    category: "Politique",
  },
  {
    minute: "13:00",
    year: 1953,
    title: "Couronnement d'Élisabeth II",
    description: "Le 2 juin 1953, Élisabeth II est couronnée à Westminster Abbey dans la première cérémonie de couronnement diffusée à la télévision.",
    curiosity: "La BBC diffusa la cérémonie en direct. Les ventes de téléviseurs explosèrent en Grande-Bretagne dans les semaines précédant l'événement.",
    category: "Culture",
  },
  {
    minute: "13:22",
    year: 1900,
    title: "Max Planck Découvre le Quantum",
    description: "En décembre 1900, Max Planck présente sa théorie des quanta, fondant la physique quantique et révolutionnant notre compréhension de la matière.",
    curiosity: "Planck lui-même n'était pas convaincu par sa propre théorie. Il pensait que c'était un 'truc mathématique' sans réalité physique.",
    category: "Science",
  },
  {
    minute: "14:02",
    year: 1953,
    title: "Ascension de l'Everest par Hillary et Tensing",
    description: "Le 29 mai 1953 à 11h30, Edmund Hillary et Tensing Norgay atteignent le sommet de l'Everest (8849 m), le toit du monde.",
    curiosity: "La nouvelle parvint à Londres le matin du couronnement d'Élisabeth II. Le journal 'The Times' avait un correspondant au camp de base.",
    category: "Exploration",
  },
  {
    minute: "14:26",
    year: 1986,
    title: "Explosion de la Navette Challenger",
    description: "Le 28 janvier 1986, 73 secondes après le décollage, la navette Challenger explose devant des millions de téléspectateurs américains.",
    curiosity: "L'enseignante Christa McAuliffe était à bord — des classes entières regardèrent en direct. Les enquêteurs trouvèrent que les 7 astronautes survécurent à l'explosion.",
    category: "Tragédie",
  },
  {
    minute: "15:28",
    year: 1970,
    title: "Jimi Hendrix Décède",
    description: "Le 18 septembre 1970, Jimi Hendrix est retrouvé mort à Londres à 27 ans, entrant dans le tristement célèbre 'Club des 27'.",
    curiosity: "Hendrix avait racheté le studio Electric Lady à New York. Il y enregistra son dernier album 5 jours avant sa mort.",
    category: "Art",
  },
  {
    minute: "15:56",
    year: 1997,
    title: "La Sonde Pathfinder se Pose sur Mars",
    description: "Le 4 juillet 1997, la sonde Mars Pathfinder se pose sur la planète rouge, avec le rover Sojourner qui explorera pendant 83 jours.",
    curiosity: "Pathfinder transmit 2,3 milliards de bits de données depuis Mars. Le rover pesait 11 kg et roulait à la vitesse de 1 cm par seconde.",
    category: "Exploration",
  },
  {
    minute: "16:44",
    year: 1989,
    title: "Premier SMS de l'Histoire",
    description: "Le 3 décembre 1992, l'ingénieur Neil Papworth envoie le premier SMS de l'histoire : 'Merry Christmas' depuis un ordinateur vers un téléphone Orbitel.",
    curiosity: "Papworth ne pouvait pas répondre depuis son téléphone — les mobiles de l'époque ne permettaient pas d'envoyer des SMS. Il fallut attendre 1993.",
    category: "Technologie",
  },
  {
    minute: "17:00",
    year: 1519,
    title: "Mort de Léonard de Vinci",
    description: "Le 2 mai 1519, Léonard de Vinci s'éteint en France à l'âge de 67 ans, laissant derrière lui des carnets qui révolutionneront la science et l'art.",
    curiosity: "Léonard écrivait en écriture miroir de droite à gauche. La Joconde ne fut accrochée au Louvre qu'après son vol et récupération en 1911.",
    category: "Art",
  },
  {
    minute: "17:42",
    year: 1837,
    title: "Premier Message Télégraphique",
    description: "En 1837, Samuel Morse invente le télégraphe électrique. En 1844, il envoie 'What hath God wrought' entre Washington et Baltimore.",
    curiosity: "Le code Morse réduisit à quelques instants une communication qui prenait des semaines. Les opérateurs de télégraphe étaient les 'hackers' du XIXe siècle.",
    category: "Technologie",
  },
  {
    minute: "18:18",
    year: 1955,
    title: "Décès d'Albert Einstein",
    description: "Le 18 avril 1955 à Princeton, Albert Einstein s'éteint à 76 ans. Il refusa une opération, disant : 'Il est de mauvais goût de vouloir vivre artificiellement.'",
    curiosity: "Le pathologiste vola le cerveau d'Einstein sans autorisation et le découpa en 240 morceaux pour l'analyser. Il le cacha pendant 23 ans.",
    category: "Science",
  },
  {
    minute: "19:07",
    year: 1992,
    title: "Lancement du World Wide Web Public",
    description: "Le 30 avril 1993, Tim Berners-Lee et le CERN annoncent que le World Wide Web sera accessible gratuitement au public, changeant le monde.",
    curiosity: "Berners-Lee aurait pu devenir milliardaire s'il avait breveté le Web. Il choisit de l'offrir à l'humanité. Ce choix fit notre internet actuel.",
    category: "Technologie",
  },
  {
    minute: "19:30",
    year: 1940,
    title: "Discours de l'Appel du 18 Juin",
    description: "Le 18 juin 1940, le Général de Gaulle lance son célèbre Appel depuis la BBC à Londres, refusant la défaite de la France face à l'Allemagne.",
    curiosity: "Moins de 100 000 Français entendirent l'Appel en direct. Pourtant, il devint le fondement de la Résistance française et d'une identité nationale.",
    category: "Politique",
  },
  {
    minute: "20:02",
    year: 1944,
    title: "Libération de Paris",
    description: "Le 25 août 1944, Paris est libérée par les forces alliées et la Résistance française après 4 ans d'occupation nazie.",
    curiosity: "Hitler ordonna de brûler Paris avant de la rendre. Le général Von Choltitz désobéit à l'ordre, sauvant l'une des plus belles villes du monde.",
    category: "Politique",
  },
  {
    minute: "20:33",
    year: 1988,
    title: "Seul autour du monde — Ellen MacArthur",
    description: "En 2005, Ellen MacArthur bat le record du tour du monde à la voile en solitaire — 71 jours 14 heures en mer sans escale.",
    curiosity: "MacArthur ne dormit jamais plus de 20 minutes consécutives pendant 71 jours. Elle perdit 4 kg et souffrit d'hallucinations vers la fin.",
    category: "Sport",
  },
  {
    minute: "21:10",
    year: 1492,
    title: "La Santa María s'Échoue à Haïti",
    description: "Le 25 décembre 1492, le navire amiral de Colomb, la Santa María, s'échoue sur les côtes d'Haïti. Les débris servirent à construire un fort.",
    curiosity: "Colomb laissa 39 hommes à Haïti en repartant. À son retour 11 mois plus tard, ils étaient tous morts, tués par les Taïnos après avoir terrorisé la population.",
    category: "Exploration",
  },
  {
    minute: "21:55",
    year: 1995,
    title: "Lancement de Windows 95",
    description: "Le 24 août 1995, Microsoft lance Windows 95. Des files d'attente se forment devant les magasins. 'Start Me Up' des Rolling Stones retentit.",
    curiosity: "Microsoft paya les Rolling Stones 8 millions de dollars pour utiliser 'Start Me Up'. 1 million de copies furent vendues en 4 jours.",
    category: "Technologie",
  },
  {
    minute: "22:14",
    year: 1928,
    title: "Fleming Découvre la Pénicilline",
    description: "En septembre 1928, Alexander Fleming remarque qu'une moisissure a tué des bactéries dans une boîte de Pétri. La pénicilline venait d'être découverte.",
    curiosity: "Fleming était parti en vacances et avait oublié des cultures. À son retour, il faillit tout jeter. Par chance, il remarqua la moisissure.",
    category: "Science",
  },
  {
    minute: "22:38",
    year: 1957,
    title: "Lancement de Spoutnik — L'Espace est Conquis",
    description: "Le 4 octobre 1957, l'URSS lance Spoutnik 1, premier satellite artificiel de la Terre, déclenchant la course à l'espace.",
    curiosity: "Le bip-bip de Spoutnik était capté par tous les radioamateurs du monde libre. La panique aux États-Unis fut immédiate — la course à l'espace était lancée.",
    category: "Technologie",
  },
  {
    minute: "23:00",
    year: 1979,
    title: "Révolution Iranienne — Le Shah Fuit",
    description: "Le 16 janvier 1979, le Shah d'Iran Mohammad Reza Pahlavi quitte le pays definitellement sous la pression de la révolution islamique.",
    curiosity: "L'Ayatollah Khomeini revint d'exil le 1er février après 14 ans d'absence. 5 millions d'Iraniens l'accueillirent à Téhéran.",
    category: "Politique",
  },
  {
    minute: "23:42",
    year: 1961,
    title: "Création de l'Organisation des Astronautes",
    description: "En 1961, la NASA sélectionne le Groupe 2 des astronautes (les 'New Nine') incluant Neil Armstrong, John Young et Pete Conrad.",
    curiosity: "Pour être sélectionné, il fallait être pilote de chasse, moins de 35 ans, moins de 1,80 m et avoir un diplôme d'ingénieur. 255 candidats pour 9 places.",
    category: "Exploration",
  },
  {
    minute: "23:50",
    year: 1901,
    title: "Mort de la Reine Victoria",
    description: "Le 22 janvier 1901, la Reine Victoria s'éteint à 81 ans après 63 ans de règne — la monarchie la plus longue de l'histoire britannique jusqu'à Élisabeth II.",
    curiosity: "Victoria portait des vêtements noirs depuis la mort de son mari Albert en 1861, soit pendant 40 ans. Elle fut enterrée avec un moulage de la main d'Albert.",
    category: "Culture",
  },
]

// Indexer par minute pour recherche rapide
const eventsByMinute = new Map<string, StaticEvent>()
for (const event of HISTORICAL_EVENTS) {
  eventsByMinute.set(event.minute, event)
}

export function getEventForMinute(minute: string): StaticEvent | null {
  return eventsByMinute.get(minute) ?? null
}

export function hasEventForMinute(minute: string): boolean {
  return eventsByMinute.has(minute)
}

export function getAllEventMinutes(): string[] {
  return Array.from(eventsByMinute.keys())
}
